# Generated by Django 2.0.13 on 2020-07-01 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_auto_20200515_1309"),
        ("global_config", "0010_auto_20200623_1222"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Change_Actual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("Change_Initiation_Date", models.DateTimeField(verbose_name="Change Start Date")),
                ("Change_Description", models.TextField(verbose_name="Change Description")),
                (
                    "Change_Risk_Assesment",
                    models.TextField(verbose_name="Risk Assessment and Mitigation"),
                ),
                ("Cut_In_Number", models.CharField(max_length=200, verbose_name="Cut In Number")),
                (
                    "Cut_Out_Number",
                    models.CharField(max_length=200, verbose_name="Cut Out Number"),
                ),
                (
                    "Change_Initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Change Initiator",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Change_Signoffs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("Signature_Date", models.DateTimeField(null=True, verbose_name="Signature Date")),
                (
                    "Changeover_Department_Required",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.Departments",
                        verbose_name="Signoff Department",
                    ),
                ),
                (
                    "Parent_Change_Actual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="change_management.Change_Actual",
                        verbose_name="Parent Change",
                    ),
                ),
                (
                    "Signature_User",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Signature User",
                    ),
                ),
                (
                    "Signoff_Pay_Grade_Required",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.Pay_Grades",
                        verbose_name="Signoff Min Pay Grade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Change_Signoffs_Required",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "Changeover_Department_Required",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.Departments",
                        verbose_name="Signoff Department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Change_Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("Status_Name", models.CharField(max_length=500, verbose_name="Status Name")),
            ],
        ),
        migrations.CreateModel(
            name="Change_Type",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "Change_Type_Name",
                    models.CharField(max_length=500, verbose_name="Change Type Name"),
                ),
                (
                    "Change_Type_Description",
                    models.TextField(verbose_name="Change Type Description"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="change_signoffs_required",
            name="Parent_Change_Type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="change_management.Change_Type"
            ),
        ),
        migrations.AddField(
            model_name="change_signoffs_required",
            name="Signoff_Pay_Grade_Required",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Pay_Grades",
                verbose_name="Signoff Min Pay Grade",
            ),
        ),
        migrations.AddField(
            model_name="change_actual",
            name="Change_Type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="change_management.Change_Type",
                verbose_name="Change Type",
            ),
        ),
        migrations.AddField(
            model_name="change_actual",
            name="Lines_Affected",
            field=models.ManyToManyField(to="global_config.Line", verbose_name="Lines Affected"),
        ),
        migrations.AddField(
            model_name="change_actual",
            name="Machines_Affected",
            field=models.ManyToManyField(
                to="global_config.Machine", verbose_name="Machines Affected"
            ),
        ),
        migrations.AddField(
            model_name="change_actual",
            name="Operations_Affected",
            field=models.ManyToManyField(
                to="global_config.Machining_Operation", verbose_name="Operations Affected"
            ),
        ),
        migrations.AddField(
            model_name="change_actual",
            name="Status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="change_management.Change_Status",
                verbose_name="Change Status",
            ),
        ),
        migrations.AddField(
            model_name="change_actual",
            name="Variants_Affected",
            field=models.ManyToManyField(
                to="global_config.Variant", verbose_name="Variants Affected"
            ),
        ),
        migrations.AlterField(
            model_name="Change_Actual",
            name="Change_Initiator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wonde.WondeAccount",
                db_index=True,
            ),
        ),
    ]
