# Generated by Django 2.0.13 on 2020-07-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("change_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="change_signoffs",
            old_name="Changeover_Department_Required",
            new_name="Signoff_Department_Required",
        ),
    ]
