# Generated by Django 2.0.13 on 2020-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EOL_At_Risk_Register",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("At_Risk_Date", models.DateTimeField(verbose_name="Date Logged at Risk")),
                (
                    "Removed_At_Risk_Date",
                    models.DateTimeField(null=True, verbose_name="Removed from at risk date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EOL_Failure_Mode_Rashmap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "Failure_Mode_Text",
                    models.CharField(
                        max_length=200,
                        verbose_name="Failure Mode Text (MUST MATCH QR CODE EXACTLY!",
                    ),
                ),
                (
                    "Failure_Mode_Image",
                    models.ImageField(
                        upload_to="EOL_Failure_Modes/%d%m%y%H%M", verbose_name="Rash Map Image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EOL_Failure_Mode_Rashmap_Record",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EOL_Record",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("Scanned_Date", models.DateTimeField(verbose_name="Date Scanned")),
                (
                    "Finished_Part_Matrix",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Grading 2D Matrix"
                    ),
                ),
                (
                    "Raw_Serial_Number",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Supplier Serial Number"
                    ),
                ),
                (
                    "Inspection_Decision",
                    models.CharField(max_length=200, verbose_name="Inspection Decision"),
                ),
                ("Age_On_Buyoff", models.IntegerField(verbose_name="Part Age on Buyoff")),
                (
                    "Part_At_Risk_Status",
                    models.CharField(max_length=200, verbose_name="Part At Risk Status"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rash_Map_Choices",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("Choice_Name", models.CharField(max_length=100)),
            ],
        ),
    ]
