# Generated by Django 2.0.13 on 2020-02-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("global_config", "0001_initial"),
        ("EOL_Database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eol_record",
            name="Part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="global_config.Part",
                verbose_name="Part Record",
                db_index=True,
            ),
        ),
    ]
