# Generated by Django 2.0.13 on 2020-12-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gauging", "0002_gauge_type_applicable_ops"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gauging_record",
            name="Part_Link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gauging.Gauging_Record",
                verbose_name="Which part was the previous?",
                db_index=True,
            ),
        ),
    ]
